server:
  port: 8761

spring:
  application:
    name: eureka-server-1

eureka:
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8762/eureka/